package com.esep.transaction;

import com.esep.common.web.PageResponse;
import com.esep.security.CurrentUser;
import com.esep.transaction.dto.DepositRequest;
import com.esep.transaction.dto.OperationResponse;
import com.esep.transaction.dto.TransactionResponse;
import com.esep.transaction.dto.TransactionResult;
import com.esep.transaction.dto.TransferRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.headers.Header;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.RequiredArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import java.net.URI;
import java.time.LocalDate;
import java.time.ZoneId;

@Tag(name = "Transactions", description = "Double-entry transfers and deposits. POST requests require an Idempotency-Key header: a retry with the same key returns the original result")
@RestController
@RequestMapping("/api")
@RequiredArgsConstructor
public class TransactionController {

    static final String IDEMPOTENCY_KEY = "Idempotency-Key";
    static final String IDEMPOTENT_REPLAYED = "Idempotent-Replayed";
    private static final String KEY_DESCRIPTION = "Unique per logical operation (e.g. a UUID generated by the client). "
            + "Repeat it when retrying the same operation: the original result is returned and money moves once.";

    private final TransactionService transactionService;
    private final OperationHistoryService historyService;

    @Operation(summary = "Transfer money from an own account (201; retry with the same key: 200 + Idempotent-Replayed)")
    @ApiResponse(responseCode = "201", description = "Transfer completed",
            headers = @Header(name = "Location", description = "URL of the created transaction"))
    @ApiResponse(responseCode = "200", description = "Replay of an earlier request with the same Idempotency-Key",
            headers = @Header(name = IDEMPOTENT_REPLAYED, description = "Always \"true\" on a replay"))
    @PostMapping("/transfers")
    public ResponseEntity<TransactionResponse> transfer(
            @AuthenticationPrincipal CurrentUser currentUser,
            @Parameter(description = KEY_DESCRIPTION, example = "3f1c2b8e-6c1d-4c7a-9a55-0b6f3e2d9a10")
            @RequestHeader(IDEMPOTENCY_KEY) @NotBlank @Size(max = 64) String idempotencyKey,
            @Valid @RequestBody TransferRequest request) {
        return created(transactionService.transfer(currentUser, idempotencyKey, request));
    }

    @Operation(summary = "Deposit money from the system funding account (ADMIN only)")
    @ApiResponse(responseCode = "201", description = "Deposit completed")
    @ApiResponse(responseCode = "200", description = "Replay of an earlier request with the same Idempotency-Key")
    @PostMapping("/deposits")
    public ResponseEntity<TransactionResponse> deposit(
            @AuthenticationPrincipal CurrentUser currentUser,
            @Parameter(description = KEY_DESCRIPTION)
            @RequestHeader(IDEMPOTENCY_KEY) @NotBlank @Size(max = 64) String idempotencyKey,
            @Valid @RequestBody DepositRequest request) {
        return created(transactionService.deposit(currentUser, idempotencyKey, request));
    }

    @Operation(summary = "Operation history of the current user, newest first (filter by account and calendar days)")
    @GetMapping("/transactions")
    public PageResponse<OperationResponse> history(
            @AuthenticationPrincipal CurrentUser currentUser,
            @RequestParam(required = false) Long accountId,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate from,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate to,
            @RequestParam(defaultValue = "UTC") ZoneId zone,
            @RequestParam(defaultValue = "0") @Min(0) int page,
            @RequestParam(defaultValue = "20") @Min(1) @Max(100) int size) {
        return historyService.history(currentUser, accountId, from, to, zone, page, size);
    }

    @Operation(summary = "Get a transaction with its ledger entries (participants and ADMIN)")
    @GetMapping("/transactions/{id}")
    public TransactionResponse getById(@AuthenticationPrincipal CurrentUser currentUser, @PathVariable Long id) {
        return transactionService.getById(currentUser, id);
    }

    // first call -> 201 Created; repeated call with the same key -> 200 OK with the saved result
    private static ResponseEntity<TransactionResponse> created(TransactionResult result) {
        TransactionResponse body = result.response();
        if (result.replayed()) {
            return ResponseEntity.ok().header(IDEMPOTENT_REPLAYED, "true").body(body);
        }
        URI location = ServletUriComponentsBuilder.fromCurrentContextPath()
                .path("/api/transactions/{id}")
                .buildAndExpand(body.id())
                .toUri();
        return ResponseEntity.created(location).body(body);
    }
}
