-- Esep API: initial schema (double-entry ledger)

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role  CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE accounts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT        NOT NULL REFERENCES users (id),
    currency   VARCHAR(3)    NOT NULL,
    balance    NUMERIC(19,4) NOT NULL DEFAULT 0,
    version    BIGINT        NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    -- last line of defense: even if the service has a bug, the DB rejects a negative balance
    CONSTRAINT ck_accounts_balance_non_negative CHECK (balance >= 0),
    CONSTRAINT ck_accounts_currency_iso         CHECK (currency ~ '^[A-Z]{3}$')
);

-- PostgreSQL does NOT create indexes for foreign keys automatically
CREATE INDEX ix_accounts_user_id ON accounts (user_id);

CREATE TABLE transactions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            VARCHAR(20) NOT NULL,
    status          VARCHAR(20) NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_transactions_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_transactions_type   CHECK (type IN ('TRANSFER', 'DEPOSIT', 'WITHDRAWAL')),
    CONSTRAINT ck_transactions_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED'))
);

-- amount is always positive; the sign comes from direction:
-- DEBIT = money leaves the account (-), CREDIT = money enters the account (+)
CREATE TABLE ledger_entries (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT        NOT NULL REFERENCES transactions (id),
    account_id     BIGINT        NOT NULL REFERENCES accounts (id),
    amount         NUMERIC(19,4) NOT NULL,
    direction      VARCHAR(6)    NOT NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_ledger_entries_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_ledger_entries_direction       CHECK (direction IN ('DEBIT', 'CREDIT'))
);

CREATE INDEX ix_ledger_entries_transaction_id ON ledger_entries (transaction_id);
CREATE INDEX ix_ledger_entries_account_id     ON ledger_entries (account_id, created_at);
