-- Transactional Outbox: an event is written in the SAME database transaction as the transfer.
-- Either both the transfer and its event are committed, or neither. A separate publisher
-- reads unpublished rows and sends them to Kafka (at-least-once delivery).
CREATE TABLE outbox_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       UUID          NOT NULL,
    aggregate_type VARCHAR(50)   NOT NULL,
    aggregate_id   BIGINT        NOT NULL,
    event_type     VARCHAR(50)   NOT NULL,
    message_key    VARCHAR(100)  NOT NULL,
    payload        JSONB         NOT NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    published_at   TIMESTAMPTZ,
    attempts       INT           NOT NULL DEFAULT 0,
    last_error     VARCHAR(1000),
    CONSTRAINT uq_outbox_events_event_id UNIQUE (event_id)
);

-- the publisher only ever looks for unpublished rows in id order: a tiny partial index
CREATE INDEX ix_outbox_events_unpublished ON outbox_events (id) WHERE published_at IS NULL;

-- Consumer-side idempotency: Kafka may deliver the same event more than once.
-- A consumer records the event id in the same transaction as its side effects.
CREATE TABLE processed_events (
    consumer     VARCHAR(100) NOT NULL,
    event_id     UUID         NOT NULL,
    processed_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (consumer, event_id)
);

CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id),
    event_id   UUID         NOT NULL,
    type       VARCHAR(30)  NOT NULL,
    message    VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- second safety net for idempotency: one notification per user per event
    CONSTRAINT uq_notifications_event_user UNIQUE (event_id, user_id),
    CONSTRAINT ck_notifications_type CHECK (type IN ('TRANSFER_SENT', 'TRANSFER_RECEIVED'))
);

CREATE INDEX ix_notifications_user_created ON notifications (user_id, created_at DESC);
